# Generated by Django 2.2.2 on 2019-07-18 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_profile_gender'),
        ('chat', '0003_auto_20190718_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='main.Profile'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
