# Generated by Django 2.2.2 on 2019-07-15 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_meeting_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='_profile_contacts_+', to='main.Profile'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='next_meeting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='main.Meeting'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='previous_meeting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='main.Meeting'),
        ),
    ]
