# Generated by Django 2.2.2 on 2019-07-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190715_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='begin',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='end',
            field=models.TimeField(auto_now=True),
        ),
    ]
