# Generated by Django 2.2.2 on 2019-07-18 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20190718_2327'),
        ('main', '0011_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='chatroom',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='chat.ChatRoom'),
        ),
    ]
