# Generated by Django 2.2.2 on 2019-07-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190720_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='doing',
            field=models.BooleanField(default=False),
        ),
    ]
