# Generated by Django 2.2.2 on 2019-07-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190720_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='begin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='end',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
