# Generated by Django 2.2.2 on 2019-07-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190720_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
