# Generated by Django 2.2.2 on 2019-07-21 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_profile_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='notification',
        ),
    ]
