# Generated by Django 2.2.2 on 2019-07-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20190721_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='static/images/anonym.png', upload_to=''),
        ),
        migrations.DeleteModel(
            name='Transcription',
        ),
    ]
